# Form implementation generated from reading ui file 'Camera_trig.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1936, 1080)
        MainWindow.setStyleSheet("            QMainWindow {\n"
"                background-color: rgb(255, 255, 255); /* Dark background for the main window */\n"
"            }\n"
"\n"
"            QGroupBox, QPushButton, QTextEdit {\n"
"                color: black; /* White text for readability */\n"
"                background-color: #e7e7e7; /* Slightly lighter dark gray for widgets */\n"
"                border: 1px solid #444444;\n"
"                padding: 5px;\n"
"                border-radius: 4px;\n"
"            }\n"
"    \n"
"            QTabWidget::pane { /* The tab widget frame */\n"
"                border-top: 2px solid #f3f3f3;\n"
"            }\n"
"            QTabBar::tab {\n"
"                background: #f3f3f3;\n"
"                color: rgb(0, 0, 0);\n"
"                border: 1px;\n"
"                min-width: 8ex;\n"
"                padding: 5px;\n"
"            }\n"
"\n"
"            QTabBar::tab:selected, QTabBar::tab:hover {\n"
"                background: #e7e7e7;\n"
"                border-top: 3px solid #0f52ba;\n"
"            }\n"
"\n"
"\n"
"            QPushButton:hover {\n"
"                background-color: #cae1ff;\n"
"                border: 1px solid #0066cc;; /* Blue border for button hover */\n"
"            }\n"
"\n"
"QScrollBar:vertical {\n"
"                background: #2e2e2e;\n"
"                width: 14px;\n"
"                margin: 15px 3px 15px 3px;\n"
"                border: 1px solid #222222;\n"
"                border-radius: 5px;\n"
"            }\n"
"\n"
"QScrollBar::handle:vertical {\n"
"                background: #5c90d2;\n"
"                min-height: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"                background: #787878;\n"
"            }\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                background: none;\n"
"            }\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }\n"
"\n"
"             QRadioButton {\n"
"                color: #b1b1b1; /* Default text color */\n"
"                spacing: 5px; /* Spacing around text and icon */\n"
"            }\n"
"            QRadioButton::indicator {\n"
"                width: 13px;\n"
"                height: 13px;\n"
"                border-radius: 7px; /* Circular indicators */\n"
"            }\n"
"            QRadioButton::indicator:unchecked {\n"
"                background-color: #cae1ff; /* Light gray background when unchecked */\n"
"                    border: 1px solid #0066cc; /* Gray border */\n"
"            }\n"
"            QRadioButton::indicator:checked {\n"
"                background-color: #5c90d2; /* Blue background when checked */\n"
"                border: 1px solid #0066cc; /* Darker blue border */\n"
"            }\n"
"\n"
"            QRadioButton::indicator:hover {\n"
"                background-color: #5c90d2; /* Darker grey background when checked */\n"
"                border: 2px solid #0066cc; /* White border when checked */\n"
"            }\n"
"            QRadioButton::indicator:checked:hover {\n"
"                background-color: #5c90d2; /* Darker grey background when checked */\n"
"                border: 1px solid #0066cc; /* White border when checked */\n"
"            }\n"
"QMessageBox {\n"
"                    background-color: #ffffff; /* White background for the message box */\n"
"                    color: rgb(255, 255, 255); /* Black text for general content */\n"
"                }\n"
"            QMessageBox QPushButton {\n"
"                    background-color: #8c8c8c;\n"
"                    border: none;\n"
"                   }\n"
"            QMessageBox QLabel {\n"
"                    background-color: #ffffff; /* White background for the message box */\n"
"                    color: rgb(0, 0, 0); /* Explicitly setting label text color to black */\n"
"                    border: none;\n"
"                }")
        self.centralWidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.tabWidget.setWhatsThis("")
        self.tabWidget.setStyleSheet("            QMainWindow {\n"
"                background-color: #333333; /* Dark background for the main window */\n"
"            }\n"
"\n"
"            QGroupBox, QPushButton, QTextEdit {\n"
"                color: black; /* White text for readability */\n"
"                background-color: #e7e7e7; /* Slightly lighter dark gray for widgets */\n"
"                border: 1px solid #444444;\n"
"                padding: 5px;\n"
"                border-radius: 4px;\n"
"            }\n"
"    \n"
"            QTabWidget::pane { /* The tab widget frame */\n"
"                border-top: 2px solid #f3f3f3;\n"
"            }\n"
"            QTabBar::tab {\n"
"                background: #f3f3f3;\n"
"                color: rgb(0, 0, 0);\n"
"                border: 1px;\n"
"                min-width: 8ex;\n"
"                padding: 5px;\n"
"            }\n"
"\n"
"            QTabBar::tab:selected, QTabBar::tab:hover {\n"
"                background: #e7e7e7;\n"
"                border-top: 3px solid #0f52ba;\n"
"            }\n"
"\n"
"\n"
"            QPushButton:hover {\n"
"                background-color: #cae1ff;\n"
"                border: 1px solid #0066cc;; /* Blue border for button hover */\n"
"            }\n"
"\n"
"QScrollBar:vertical {\n"
"                background: #2e2e2e;\n"
"                width: 14px;\n"
"                margin: 15px 3px 15px 3px;\n"
"                border: 1px solid #222222;\n"
"                border-radius: 5px;\n"
"            }\n"
"\n"
"QScrollBar::handle:vertical {\n"
"                background: #5c90d2;\n"
"                min-height: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"                background: #787878;\n"
"            }\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                background: none;\n"
"            }\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }\n"
"\n"
"             QRadioButton {\n"
"                color: #b1b1b1; /* Default text color */\n"
"                spacing: 5px; /* Spacing around text and icon */\n"
"            }\n"
"            QRadioButton::indicator {\n"
"                width: 13px;\n"
"                height: 13px;\n"
"                border-radius: 7px; /* Circular indicators */\n"
"            }\n"
"            QRadioButton::indicator:unchecked {\n"
"                background-color: #cae1ff; /* Light gray background when unchecked */\n"
"                    border: 1px solid #0066cc; /* Gray border */\n"
"            }\n"
"            QRadioButton::indicator:checked {\n"
"                background-color: #5c90d2; /* Blue background when checked */\n"
"                border: 1px solid #0066cc; /* Darker blue border */\n"
"            }\n"
"\n"
"            QRadioButton::indicator:hover {\n"
"                background-color: #5c90d2; /* Darker grey background when checked */\n"
"                border: 2px solid #0066cc; /* White border when checked */\n"
"            }\n"
"            QRadioButton::indicator:checked:hover {\n"
"                background-color: #5c90d2; /* Darker grey background when checked */\n"
"                border: 1px solid #0066cc; /* White border when checked */\n"
"            }\n"
"QMessageBox {\n"
"                    background-color: #ffffff; /* White background for the message box */\n"
"                    color: rgb(255, 255, 255); /* Black text for general content */\n"
"                }\n"
"            QMessageBox QPushButton {\n"
"                    background-color: #8c8c8c;\n"
"                    border: none;\n"
"                   }\n"
"            QMessageBox QLabel {\n"
"                    background-color: #ffffff; /* White background for the message box */\n"
"                    color: rgb(0, 0, 0); /* Explicitly setting label text color to black */\n"
"                    border: none;\n"
"                }")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Operation = QtWidgets.QWidget()
        self.tab_Operation.setObjectName("tab_Operation")
        self.label_img_out = QtWidgets.QLabel(parent=self.tab_Operation)
        self.label_img_out.setGeometry(QtCore.QRect(20, 100, 1200, 900))
        self.label_img_out.setStyleSheet("\n"
"border: 1px solid rgb(0, 0, 0);\n"
"background-color: rgb(182, 182, 182);")
        self.label_img_out.setText("")
        self.label_img_out.setObjectName("label_img_out")
        self.label_check = QtWidgets.QLabel(parent=self.tab_Operation)
        self.label_check.setGeometry(QtCore.QRect(1470, 860, 441, 141))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        self.label_check.setFont(font)
        self.label_check.setStyleSheet("background-color: rgb(85, 170, 0);\n"
"border: 1px solid rgb(0, 0, 0);")
        self.label_check.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_check.setIndent(10)
        self.label_check.setObjectName("label_check")
        self.label_ProcessTime = QtWidgets.QLabel(parent=self.tab_Operation)
        self.label_ProcessTime.setGeometry(QtCore.QRect(1470, 960, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.label_ProcessTime.setFont(font)
        self.label_ProcessTime.setStyleSheet("color: rgb(0, 0, 0); \n"
"")
        self.label_ProcessTime.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_ProcessTime.setScaledContents(False)
        self.label_ProcessTime.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_ProcessTime.setIndent(-1)
        self.label_ProcessTime.setObjectName("label_ProcessTime")
        self.label_logo = QtWidgets.QLabel(parent=self.tab_Operation)
        self.label_logo.setGeometry(QtCore.QRect(1140, 20, 81, 81))
        self.label_logo.setStyleSheet("")
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.label_logo_2 = QtWidgets.QLabel(parent=self.tab_Operation)
        self.label_logo_2.setGeometry(QtCore.QRect(910, 910, 81, 81))
        self.label_logo_2.setText("")
        self.label_logo_2.setObjectName("label_logo_2")
        self.label = QtWidgets.QLabel(parent=self.tab_Operation)
        self.label.setGeometry(QtCore.QRect(20, 20, 1200, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"border: 1px solid rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 0);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.widget_4 = QtWidgets.QWidget(parent=self.tab_Operation)
        self.widget_4.setGeometry(QtCore.QRect(1220, 20, 691, 241))
        self.widget_4.setStyleSheet("\n"
"border: 1px solid rgb(0, 0, 0);")
        self.widget_4.setObjectName("widget_4")
        self.widget = QtWidgets.QWidget(parent=self.widget_4)
        self.widget.setGeometry(QtCore.QRect(70, 70, 221, 151))
        self.widget.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(0, 0, 0)")
        self.widget.setObjectName("widget")
        self.label_11 = QtWidgets.QLabel(parent=self.widget)
        self.label_11.setGeometry(QtCore.QRect(30, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border: none;")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.comboBox_type = QtWidgets.QComboBox(parent=self.widget)
        self.comboBox_type.setGeometry(QtCore.QRect(30, 80, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_type.setFont(font)
        self.comboBox_type.setStyleSheet("QComboBox {\n"
"                border: 1px solid ;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                min-width: 6em;\n"
"                background-color: none;\n"
"            }\n"
"\n"
"            QComboBox:hover {\n"
"                background-color: #cae1ff;\n"
"                border: 1px solid #0066cc; /* Blue border for button hover */\n"
"            }\n"
"\n"
"            QComboBox::drop-down {\n"
"                subcontrol-origin: padding;\n"
"                subcontrol-position: top right;\n"
"                width: 25px;\n"
"                border-left: 1px solid;\n"
"                border-top-right-radius: 3px;\n"
"                border-bottom-right-radius: 3px;\n"
"            }\n"
"\n"
"            QComboBox::down-arrow {\n"
"                image: url(D:/Pharma3/icon/icons8-arrow-down);\n"
"                width: 14px;\n"
"                height: 14px;\n"
"                margin-top: 2px;    \n"
"            }\n"
"\n"
"          ")
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.bnSettings = QtWidgets.QPushButton(parent=self.widget)
        self.bnSettings.setEnabled(True)
        self.bnSettings.setGeometry(QtCore.QRect(170, 10, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.bnSettings.setFont(font)
        self.bnSettings.setStyleSheet("QPushButton {\n"
"    background-color: none;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #cae1ff;\n"
"    border: 1px solid #0066cc; /* Blue border for button hover */\n"
"}\n"
"")
        self.bnSettings.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/setting.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bnSettings.setIcon(icon)
        self.bnSettings.setIconSize(QtCore.QSize(30, 30))
        self.bnSettings.setObjectName("bnSettings")
        self.bnStart = QtWidgets.QPushButton(parent=self.widget_4)
        self.bnStart.setEnabled(False)
        self.bnStart.setGeometry(QtCore.QRect(330, 70, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.bnStart.setFont(font)
        self.bnStart.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.bnStart.setStyleSheet("")
        self.bnStart.setObjectName("bnStart")
        self.bnStop = QtWidgets.QPushButton(parent=self.widget_4)
        self.bnStop.setEnabled(False)
        self.bnStop.setGeometry(QtCore.QRect(500, 70, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.bnStop.setFont(font)
        self.bnStop.setStyleSheet("")
        self.bnStop.setObjectName("bnStop")
        self.bnClose = QtWidgets.QPushButton(parent=self.widget_4)
        self.bnClose.setEnabled(True)
        self.bnClose.setGeometry(QtCore.QRect(500, 160, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.bnClose.setFont(font)
        self.bnClose.setStyleSheet("")
        self.bnClose.setObjectName("bnClose")
        self.bnSoftwareTrigger = QtWidgets.QPushButton(parent=self.widget_4)
        self.bnSoftwareTrigger.setEnabled(True)
        self.bnSoftwareTrigger.setGeometry(QtCore.QRect(330, 160, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.bnSoftwareTrigger.setFont(font)
        self.bnSoftwareTrigger.setStyleSheet("")
        self.bnSoftwareTrigger.setObjectName("bnSoftwareTrigger")
        self.label_signal_stop = QtWidgets.QLabel(parent=self.widget_4)
        self.label_signal_stop.setGeometry(QtCore.QRect(610, 80, 21, 21))
        self.label_signal_stop.setStyleSheet("border: none;")
        self.label_signal_stop.setText("")
        self.label_signal_stop.setObjectName("label_signal_stop")
        self.label_signal_start = QtWidgets.QLabel(parent=self.widget_4)
        self.label_signal_start.setGeometry(QtCore.QRect(440, 80, 21, 21))
        self.label_signal_start.setStyleSheet("border:none;")
        self.label_signal_start.setText("")
        self.label_signal_start.setObjectName("label_signal_start")
        self.label_12 = QtWidgets.QLabel(parent=self.widget_4)
        self.label_12.setGeometry(QtCore.QRect(20, 0, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border:none;")
        self.label_12.setObjectName("label_12")
        self.widget_5 = QtWidgets.QWidget(parent=self.tab_Operation)
        self.widget_5.setGeometry(QtCore.QRect(1220, 260, 691, 601))
        self.widget_5.setStyleSheet("\n"
"border: 1px solid rgb(0, 0, 0);")
        self.widget_5.setObjectName("widget_5")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.widget_5)
        self.tableWidget.setGeometry(QtCore.QRect(30, 60, 631, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"                background-color: #f0f0f0;\n"
"                alternate-background-color: #e0e0e0;\n"
"                selection-background-color: #a6a6a6;\n"
"            }\n"
"            QHeaderView::section {\n"
"                background-color: #404040;\n"
"                color: white;\n"
"                padding: 5px;\n"
"                border: 1px solid #606060;\n"
"            }\n"
"            QTableWidget::item {\n"
"                padding: 5px;\n"
"            }\n"
"            QTableWidget::item:selected {\n"
"                color: black;\n"
"            }")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.label_percent = QtWidgets.QLabel(parent=self.widget_5)
        self.label_percent.setGeometry(QtCore.QRect(330, 540, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_percent.setFont(font)
        self.label_percent.setStyleSheet("border: none;")
        self.label_percent.setObjectName("label_percent")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_3.setGeometry(QtCore.QRect(30, 540, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: none;")
        self.label_3.setObjectName("label_3")
        self.label_totalOK = QtWidgets.QLabel(parent=self.widget_5)
        self.label_totalOK.setGeometry(QtCore.QRect(70, 540, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_totalOK.setFont(font)
        self.label_totalOK.setStyleSheet("border: none;")
        self.label_totalOK.setObjectName("label_totalOK")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_2.setGeometry(QtCore.QRect(120, 540, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: none;")
        self.label_2.setObjectName("label_2")
        self.label_totalNG = QtWidgets.QLabel(parent=self.widget_5)
        self.label_totalNG.setGeometry(QtCore.QRect(160, 540, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_totalNG.setFont(font)
        self.label_totalNG.setStyleSheet("border: none;")
        self.label_totalNG.setObjectName("label_totalNG")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_7.setGeometry(QtCore.QRect(220, 540, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border: none;")
        self.label_7.setObjectName("label_7")
        self.bnSave_data = QtWidgets.QPushButton(parent=self.widget_5)
        self.bnSave_data.setEnabled(True)
        self.bnSave_data.setGeometry(QtCore.QRect(530, 540, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.bnSave_data.setFont(font)
        self.bnSave_data.setStyleSheet("QPushButton {\n"
"    background-color: none;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #cae1ff;\n"
"    border: 1px solid #0066cc; /* Blue border for button hover */\n"
"}\n"
"")
        self.bnSave_data.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/save.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bnSave_data.setIcon(icon1)
        self.bnSave_data.setIconSize(QtCore.QSize(30, 30))
        self.bnSave_data.setObjectName("bnSave_data")
        self.bnAdd_data = QtWidgets.QPushButton(parent=self.widget_5)
        self.bnAdd_data.setEnabled(True)
        self.bnAdd_data.setGeometry(QtCore.QRect(580, 540, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.bnAdd_data.setFont(font)
        self.bnAdd_data.setStyleSheet("QPushButton {\n"
"    background-color: none;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #cae1ff;\n"
"    border: 1px solid #0066cc; /* Blue border for button hover */\n"
"}\n"
"")
        self.bnAdd_data.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/icons8-plus-math-50.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bnAdd_data.setIcon(icon2)
        self.bnAdd_data.setIconSize(QtCore.QSize(30, 30))
        self.bnAdd_data.setObjectName("bnAdd_data")
        self.bnClear_data = QtWidgets.QPushButton(parent=self.widget_5)
        self.bnClear_data.setEnabled(True)
        self.bnClear_data.setGeometry(QtCore.QRect(630, 540, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.bnClear_data.setFont(font)
        self.bnClear_data.setStyleSheet("QPushButton {\n"
"    background-color: none;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #cae1ff;\n"
"    border: 1px solid #0066cc; /* Blue border for button hover */\n"
"}\n"
"")
        self.bnClear_data.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/icons8-close-48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bnClear_data.setIcon(icon3)
        self.bnClear_data.setIconSize(QtCore.QSize(30, 30))
        self.bnClear_data.setObjectName("bnClear_data")
        self.label_13 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_13.setGeometry(QtCore.QRect(20, 0, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("border:none;")
        self.label_13.setObjectName("label_13")
        self.labelDate = QtWidgets.QLabel(parent=self.widget_5)
        self.labelDate.setGeometry(QtCore.QRect(370, 10, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.labelDate.setFont(font)
        self.labelDate.setStyleSheet("border: none;")
        self.labelDate.setText("")
        self.labelDate.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelDate.setObjectName("labelDate")
        self.label_14 = QtWidgets.QLabel(parent=self.tab_Operation)
        self.label_14.setGeometry(QtCore.QRect(1220, 860, 251, 141))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: rgb(85, 170, 0);\n"
"border: 1px solid rgb(0, 0, 0);")
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_check.raise_()
        self.widget_5.raise_()
        self.widget_4.raise_()
        self.label.raise_()
        self.label_img_out.raise_()
        self.label_ProcessTime.raise_()
        self.label_logo.raise_()
        self.label_logo_2.raise_()
        self.label_14.raise_()
        self.tabWidget.addTab(self.tab_Operation, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.tab)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 20, 531, 281))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.label_8 = QtWidgets.QLabel(parent=self.page_0)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);\n"
"border: none;")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.widget_0 = QtWidgets.QWidget(parent=self.page_0)
        self.widget_0.setGeometry(QtCore.QRect(30, 60, 481, 201))
        self.widget_0.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(0, 0, 0)")
        self.widget_0.setObjectName("widget_0")
        self.Eccentricity_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.Eccentricity_0.setEnabled(True)
        self.Eccentricity_0.setGeometry(QtCore.QRect(390, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Eccentricity_0.setFont(font)
        self.Eccentricity_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Eccentricity_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Eccentricity_0.setObjectName("Eccentricity_0")
        self.Threshold_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.Threshold_0.setEnabled(True)
        self.Threshold_0.setGeometry(QtCore.QRect(130, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Threshold_0.setFont(font)
        self.Threshold_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Threshold_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Threshold_0.setObjectName("Threshold_0")
        self.label_17 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_17.setGeometry(QtCore.QRect(10, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_17.setObjectName("label_17")
        self.label_16 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_16.setGeometry(QtCore.QRect(10, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_16.setObjectName("label_16")
        self.Broken_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.Broken_0.setEnabled(True)
        self.Broken_0.setGeometry(QtCore.QRect(130, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Broken_0.setFont(font)
        self.Broken_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Broken_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Broken_0.setObjectName("Broken_0")
        self.label_19 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_19.setGeometry(QtCore.QRect(270, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_19.setObjectName("label_19")
        self.ROI_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.ROI_0.setEnabled(True)
        self.ROI_0.setGeometry(QtCore.QRect(130, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.ROI_0.setFont(font)
        self.ROI_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.ROI_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ROI_0.setObjectName("ROI_0")
        self.label_25 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_25.setObjectName("label_25")
        self.save0 = QtWidgets.QPushButton(parent=self.widget_0)
        self.save0.setGeometry(QtCore.QRect(400, 170, 75, 24))
        self.save0.setStyleSheet("QPushButton:hover {\n"
"                background-color: #cae1ff;\n"
"                border: 1px solid #0066cc;; /* Blue border for button hover */\n"
"            }\n"
"QPushButton {\n"
"                color: black; /* White text for readability */\n"
"                background-color: #e7e7e7; /* Slightly lighter dark gray for widgets */\n"
"                border: 1px solid #444444;\n"
"                padding: 5px;\n"
"                border-radius: 4px;\n"
"            }")
        self.save0.setObjectName("save0")
        self.label_34 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_34.setGeometry(QtCore.QRect(270, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_34.setObjectName("label_34")
        self.maxBlob_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.maxBlob_0.setEnabled(True)
        self.maxBlob_0.setGeometry(QtCore.QRect(390, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.maxBlob_0.setFont(font)
        self.maxBlob_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.maxBlob_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.maxBlob_0.setObjectName("maxBlob_0")
        self.minBlob_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.minBlob_0.setEnabled(True)
        self.minBlob_0.setGeometry(QtCore.QRect(390, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.minBlob_0.setFont(font)
        self.minBlob_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.minBlob_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.minBlob_0.setObjectName("minBlob_0")
        self.label_33 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_33.setGeometry(QtCore.QRect(270, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_33.setObjectName("label_33")
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label_9 = QtWidgets.QLabel(parent=self.page_1)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);\n"
"border: none;")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.widget_1 = QtWidgets.QWidget(parent=self.page_1)
        self.widget_1.setGeometry(QtCore.QRect(30, 60, 481, 201))
        self.widget_1.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(0, 0, 0)")
        self.widget_1.setObjectName("widget_1")
        self.Eccentricity_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.Eccentricity_1.setEnabled(True)
        self.Eccentricity_1.setGeometry(QtCore.QRect(130, 160, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Eccentricity_1.setFont(font)
        self.Eccentricity_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Eccentricity_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Eccentricity_1.setObjectName("Eccentricity_1")
        self.Threshold_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.Threshold_1.setEnabled(True)
        self.Threshold_1.setGeometry(QtCore.QRect(130, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Threshold_1.setFont(font)
        self.Threshold_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Threshold_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Threshold_1.setObjectName("Threshold_1")
        self.label_18 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_18.setGeometry(QtCore.QRect(10, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_20.setGeometry(QtCore.QRect(270, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_20.setObjectName("label_20")
        self.Broken_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.Broken_1.setEnabled(True)
        self.Broken_1.setGeometry(QtCore.QRect(390, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Broken_1.setFont(font)
        self.Broken_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Broken_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Broken_1.setObjectName("Broken_1")
        self.label_21 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_21.setGeometry(QtCore.QRect(10, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_21.setObjectName("label_21")
        self.save1 = QtWidgets.QPushButton(parent=self.widget_1)
        self.save1.setGeometry(QtCore.QRect(400, 170, 75, 24))
        self.save1.setObjectName("save1")
        self.min_area_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.min_area_1.setEnabled(True)
        self.min_area_1.setGeometry(QtCore.QRect(130, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.min_area_1.setFont(font)
        self.min_area_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.min_area_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.min_area_1.setObjectName("min_area_1")
        self.label_27 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_27.setGeometry(QtCore.QRect(10, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_27.setObjectName("label_27")
        self.label_30 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_30.setGeometry(QtCore.QRect(10, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_30.setObjectName("label_30")
        self.ROI_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.ROI_1.setEnabled(True)
        self.ROI_1.setGeometry(QtCore.QRect(130, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.ROI_1.setFont(font)
        self.ROI_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.ROI_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ROI_1.setObjectName("ROI_1")
        self.label_31 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_31.setGeometry(QtCore.QRect(270, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_31.setObjectName("label_31")
        self.maxBlob_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.maxBlob_1.setEnabled(True)
        self.maxBlob_1.setGeometry(QtCore.QRect(390, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.maxBlob_1.setFont(font)
        self.maxBlob_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.maxBlob_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.maxBlob_1.setObjectName("maxBlob_1")
        self.label_32 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_32.setGeometry(QtCore.QRect(270, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_32.setObjectName("label_32")
        self.minBlob_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.minBlob_1.setEnabled(True)
        self.minBlob_1.setGeometry(QtCore.QRect(390, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.minBlob_1.setFont(font)
        self.minBlob_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.minBlob_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.minBlob_1.setObjectName("minBlob_1")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_10 = QtWidgets.QLabel(parent=self.page_2)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);\n"
"border: none;")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.widget_2 = QtWidgets.QWidget(parent=self.page_2)
        self.widget_2.setGeometry(QtCore.QRect(30, 60, 481, 201))
        self.widget_2.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(0, 0, 0)")
        self.widget_2.setObjectName("widget_2")
        self.Threshold_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.Threshold_2.setEnabled(True)
        self.Threshold_2.setGeometry(QtCore.QRect(130, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Threshold_2.setFont(font)
        self.Threshold_2.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Threshold_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Threshold_2.setObjectName("Threshold_2")
        self.label_22 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_22.setGeometry(QtCore.QRect(10, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_22.setObjectName("label_22")
        self.ROI_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.ROI_2.setEnabled(True)
        self.ROI_2.setGeometry(QtCore.QRect(130, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.ROI_2.setFont(font)
        self.ROI_2.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.ROI_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ROI_2.setObjectName("ROI_2")
        self.label_26 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_26.setObjectName("label_26")
        self.save2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.save2.setGeometry(QtCore.QRect(390, 160, 75, 31))
        self.save2.setObjectName("save2")
        self.label_28 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_28.setGeometry(QtCore.QRect(10, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_28.setObjectName("label_28")
        self.min_area_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.min_area_2.setEnabled(True)
        self.min_area_2.setGeometry(QtCore.QRect(130, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.min_area_2.setFont(font)
        self.min_area_2.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.min_area_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.min_area_2.setObjectName("min_area_2")
        self.label_29 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_29.setGeometry(QtCore.QRect(270, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_29.setObjectName("label_29")
        self.max_area_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.max_area_2.setEnabled(True)
        self.max_area_2.setGeometry(QtCore.QRect(390, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.max_area_2.setFont(font)
        self.max_area_2.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.max_area_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.max_area_2.setObjectName("max_area_2")
        self.hue = QtWidgets.QLineEdit(parent=self.widget_2)
        self.hue.setEnabled(True)
        self.hue.setGeometry(QtCore.QRect(390, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.hue.setFont(font)
        self.hue.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.hue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hue.setObjectName("hue")
        self.label_35 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_35.setGeometry(QtCore.QRect(270, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_35.setObjectName("label_35")
        self.value = QtWidgets.QLineEdit(parent=self.widget_2)
        self.value.setEnabled(True)
        self.value.setGeometry(QtCore.QRect(390, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.value.setFont(font)
        self.value.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.value.setObjectName("value")
        self.label_36 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_36.setGeometry(QtCore.QRect(270, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_36.setObjectName("label_36")
        self.stackedWidget.addWidget(self.page_2)
        self.groupParam = QtWidgets.QGroupBox(parent=self.tab)
        self.groupParam.setEnabled(True)
        self.groupParam.setGeometry(QtCore.QRect(80, 350, 211, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupParam.sizePolicy().hasHeightForWidth())
        self.groupParam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.groupParam.setFont(font)
        self.groupParam.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.groupParam.setAutoFillBackground(False)
        self.groupParam.setStyleSheet("background-color: none;\n"
"border-radius: 5px;\n"
"border: 0.5px solid rgb(0, 0, 0)")
        self.groupParam.setTitle("")
        self.groupParam.setObjectName("groupParam")
        self.edtExposureTime = QtWidgets.QLineEdit(parent=self.groupParam)
        self.edtExposureTime.setGeometry(QtCore.QRect(100, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.edtExposureTime.setFont(font)
        self.edtExposureTime.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.edtExposureTime.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.edtExposureTime.setObjectName("edtExposureTime")
        self.label_6 = QtWidgets.QLabel(parent=self.groupParam)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_6.setStyleSheet("border: none;\n"
"background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_6.setIndent(5)
        self.label_6.setObjectName("label_6")
        self.edtGain = QtWidgets.QLineEdit(parent=self.groupParam)
        self.edtGain.setGeometry(QtCore.QRect(100, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.edtGain.setFont(font)
        self.edtGain.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.edtGain.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.edtGain.setObjectName("edtGain")
        self.label_5 = QtWidgets.QLabel(parent=self.groupParam)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_5.setStyleSheet("border: none;\n"
"background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_5.setIndent(4)
        self.label_5.setObjectName("label_5")
        self.edtFrameRate = QtWidgets.QLineEdit(parent=self.groupParam)
        self.edtFrameRate.setGeometry(QtCore.QRect(100, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.edtFrameRate.setFont(font)
        self.edtFrameRate.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.edtFrameRate.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.edtFrameRate.setObjectName("edtFrameRate")
        self.label_4 = QtWidgets.QLabel(parent=self.groupParam)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_4.setStyleSheet("border: none;\n"
"background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_4.setIndent(5)
        self.label_4.setObjectName("label_4")
        self.bnSetParam = QtWidgets.QPushButton(parent=self.groupParam)
        self.bnSetParam.setEnabled(True)
        self.bnSetParam.setGeometry(QtCore.QRect(100, 193, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.bnSetParam.setFont(font)
        self.bnSetParam.setToolTip("")
        self.bnSetParam.setStyleSheet("QPushButton:hover {\n"
"                background-color: #cae1ff;\n"
"                border: 1px solid #0066cc;; /* Blue border for button hover */\n"
"            }\n"
"QPushButton {\n"
"                color: black; /* White text for readability */\n"
"                background-color: #e7e7e7; /* Slightly lighter dark gray for widgets */\n"
"                border: 1px solid #444444;\n"
"                padding: 5px;\n"
"                border-radius: 4px;\n"
"            }")
        self.bnSetParam.setObjectName("bnSetParam")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_check.setText(_translate("MainWindow", "OK"))
        self.label_ProcessTime.setText(_translate("MainWindow", "132ms"))
        self.label.setText(_translate("MainWindow", "VISION SYSTEM"))
        self.label_11.setText(_translate("MainWindow", "OPTIONS:"))
        self.comboBox_type.setItemText(0, _translate("MainWindow", "Oval Tablet"))
        self.comboBox_type.setItemText(1, _translate("MainWindow", "Circle Tablet"))
        self.comboBox_type.setItemText(2, _translate("MainWindow", "Capsule"))
        self.bnStart.setText(_translate("MainWindow", "START"))
        self.bnStop.setText(_translate("MainWindow", "STOP"))
        self.bnClose.setText(_translate("MainWindow", "CLOSE DEVICE"))
        self.bnSoftwareTrigger.setText(_translate("MainWindow", "TRIGGER"))
        self.label_12.setText(_translate("MainWindow", "OPERATIONS"))
        self.label_percent.setText(_translate("MainWindow", "100%"))
        self.label_3.setText(_translate("MainWindow", "OK:"))
        self.label_totalOK.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "NG: "))
        self.label_totalNG.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Percentage:"))
        self.label_13.setText(_translate("MainWindow", "DATA"))
        self.label_14.setText(_translate("MainWindow", "RESULT:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Operation), _translate("MainWindow", "Operation"))
        self.label_8.setText(_translate("MainWindow", "Configuration Oval"))
        self.Eccentricity_0.setText(_translate("MainWindow", "0.3939"))
        self.Threshold_0.setText(_translate("MainWindow", "0.91"))
        self.label_17.setText(_translate("MainWindow", "Threshold:"))
        self.label_16.setText(_translate("MainWindow", "Broken:"))
        self.Broken_0.setText(_translate("MainWindow", "7"))
        self.label_19.setText(_translate("MainWindow", "Eccentricity:"))
        self.ROI_0.setText(_translate("MainWindow", "1"))
        self.label_25.setText(_translate("MainWindow", "ROI:"))
        self.save0.setText(_translate("MainWindow", "Save"))
        self.label_34.setText(_translate("MainWindow", "MinBlobArea:"))
        self.maxBlob_0.setText(_translate("MainWindow", "2000"))
        self.minBlob_0.setText(_translate("MainWindow", "10"))
        self.label_33.setText(_translate("MainWindow", "MaxBlobArea:"))
        self.label_9.setText(_translate("MainWindow", "Configuration Circle"))
        self.Eccentricity_1.setText(_translate("MainWindow", "0.87"))
        self.Threshold_1.setText(_translate("MainWindow", "0.9"))
        self.label_18.setText(_translate("MainWindow", "Threshold:"))
        self.label_20.setText(_translate("MainWindow", "Cracks:"))
        self.Broken_1.setText(_translate("MainWindow", "7"))
        self.label_21.setText(_translate("MainWindow", "Eccentricity:"))
        self.save1.setText(_translate("MainWindow", "Save"))
        self.min_area_1.setText(_translate("MainWindow", "5000"))
        self.label_27.setText(_translate("MainWindow", "Min Area:"))
        self.label_30.setText(_translate("MainWindow", "ROI:"))
        self.ROI_1.setText(_translate("MainWindow", "1"))
        self.label_31.setText(_translate("MainWindow", "MaxBlobArea:"))
        self.maxBlob_1.setText(_translate("MainWindow", "3000"))
        self.label_32.setText(_translate("MainWindow", "MinBlobArea:"))
        self.minBlob_1.setText(_translate("MainWindow", "20"))
        self.label_10.setText(_translate("MainWindow", "Configuration Capsule"))
        self.Threshold_2.setText(_translate("MainWindow", "0.85"))
        self.label_22.setText(_translate("MainWindow", "Threshold:"))
        self.ROI_2.setText(_translate("MainWindow", "1"))
        self.label_26.setText(_translate("MainWindow", "ROI:"))
        self.save2.setText(_translate("MainWindow", "Save"))
        self.label_28.setText(_translate("MainWindow", "Min area:"))
        self.min_area_2.setText(_translate("MainWindow", "1000"))
        self.label_29.setText(_translate("MainWindow", "Max area:"))
        self.max_area_2.setText(_translate("MainWindow", "3000"))
        self.hue.setText(_translate("MainWindow", "20"))
        self.label_35.setText(_translate("MainWindow", "Value:"))
        self.value.setText(_translate("MainWindow", "20"))
        self.label_36.setText(_translate("MainWindow", "Hue:"))
        self.edtExposureTime.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>Frame<br/>rate:</p></body></html>"))
        self.edtGain.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Gain:"))
        self.edtFrameRate.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Exposure<br/>time:</p></body></html>"))
        self.bnSetParam.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Settings"))
