# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QDoubleValidator,QIntValidator

class ClickableLabel(QtWidgets.QLabel):
    clicked = QtCore.pyqtSignal()
    crop_rect_changed = QtCore.pyqtSignal(int, int, int, int)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.start_point = None
        self.end_point = None
        self.cropping = False
        self.rect_roi = None
        self.dragging = False
        self.resizing = False
        self.resize_direction = None
        self.rect_handle_size = 5
        self.active_clearRect = False
        self.active_draw_rect = False       
        self.setCursor(QtCore.Qt.CursorShape.CrossCursor) 
        self.setMouseTracking(True)  # Enable mouse tracking to capture mouse move events

    def mousePressEvent(self, event):
        if self.active_draw_rect:
            if event.buttons() == QtCore.Qt.MouseButton.LeftButton:
                if self.rect_roi and self.rect_roi.contains(event.pos()):
                    if self._is_on_handle(event.pos()):
                        self.resizing = True
                        self.resize_direction = self._get_resize_direction(event.pos())
                    else:
                        self.dragging = True
                        self.offset = event.pos() - self.rect_roi.topLeft()
                else:
                    self.start_point = event.pos()
                    self.end_point = event.pos()
                    self.cropping = True
                self.update()

    def mouseMoveEvent(self, event):
        if self.active_draw_rect:
            if self.cropping:
                self.end_point = event.pos()
                self.update()
            elif self.dragging and self.rect_roi:
                self.rect_roi.moveTo(event.pos() - self.offset)
                self.update()
            elif self.resizing and self.rect_roi:
                self._resize_rect(event.pos())
                self.update()
            else:
                if self.rect_roi:
                    handle_index = self._get_handle_index(event.pos())
                    if handle_index == 0:
                        self.setCursor(QtCore.Qt.CursorShape.SizeFDiagCursor)  # Top-left corner
                    elif handle_index == 1:
                        self.setCursor(QtCore.Qt.CursorShape.SizeBDiagCursor)  # Top-right corner
                    elif handle_index == 2:
                        self.setCursor(QtCore.Qt.CursorShape.SizeBDiagCursor)  # Bottom-left corner
                    elif handle_index == 3:
                        self.setCursor(QtCore.Qt.CursorShape.SizeFDiagCursor)  # Bottom-right corner
                    elif handle_index == 4:
                        self.setCursor(QtCore.Qt.CursorShape.SizeVerCursor)  # Top edge
                    elif handle_index == 5:
                        self.setCursor(QtCore.Qt.CursorShape.SizeHorCursor)  # Right edge
                    elif handle_index == 6:
                        self.setCursor(QtCore.Qt.CursorShape.SizeVerCursor)  # Bottom edge
                    elif handle_index == 7:
                        self.setCursor(QtCore.Qt.CursorShape.SizeHorCursor)  # Left edge
                    else:
                        self.setCursor(QtCore.Qt.CursorShape.ArrowCursor)  # Default cursor otherwise

    def mouseReleaseEvent(self, event):
        if self.active_draw_rect:
            if event.button() == QtCore.Qt.MouseButton.LeftButton:
                if self.cropping:
                    self.end_point = event.pos()
                    self.cropping = False
                    if self.start_point and self.end_point:
                        self.rect_roi = QtCore.QRect(self.start_point, self.end_point).normalized()
                        self.crop_rect_changed.emit(self.rect_roi.x(), self.rect_roi.y(), self.rect_roi.width(), self.rect_roi.height())
                self.dragging = False
                self.resizing = False
                self.update()

    def paintEvent(self, event):
        super().paintEvent(event)
        painter = QtGui.QPainter(self)
        painter.setRenderHint(QtGui.QPainter.RenderHint.Antialiasing)
        if self.active_clearRect:
            self.rect_roi = None
            self.start_point = None
            self.end_point = None
            self.active_clearRect = False
            self.update()
        
        if self.rect_roi or (self.cropping and self.start_point and self.end_point):
            painter.setPen(QtGui.QPen(QtCore.Qt.GlobalColor.red, 1, QtCore.Qt.PenStyle.SolidLine))
            if self.cropping:
                rect = QtCore.QRect(self.start_point, self.end_point).normalized()
            else:
                rect = self.rect_roi
            painter.drawRect(rect)
            if rect:
                self._draw_handles(painter, rect)

    def _draw_handles(self, painter, rect):
        handles = self._get_handles(rect)
        painter.setBrush(QtGui.QBrush(QtCore.Qt.GlobalColor.white))
        for handle in handles:
            painter.drawRect(handle)

    def _get_handles(self, rect):
        handle_size = self.rect_handle_size 
        return [
            QtCore.QRect(rect.topLeft().x() + 5 - handle_size // 2, rect.topLeft().y() + 5 - handle_size // 2, handle_size, handle_size),  # Top-left corner
            QtCore.QRect(rect.topRight().x() - 5 - handle_size // 2, rect.topRight().y() + 5 - handle_size // 2, handle_size, handle_size),  # Top-right corner
            QtCore.QRect(rect.bottomLeft().x() + 5 - handle_size // 2, rect.bottomLeft().y() - 5 - handle_size // 2, handle_size, handle_size),  # Bottom-left corner
            QtCore.QRect(rect.bottomRight().x() - 5 - handle_size // 2, rect.bottomRight().y() - 5 - handle_size // 2, handle_size, handle_size),  # Bottom-right corner
            QtCore.QRect(rect.center().x() - handle_size // 2, rect.top() + 5 - handle_size // 2, handle_size, handle_size),  # Top edge
            QtCore.QRect(rect.right() - 5 - handle_size // 2, rect.center().y() - handle_size // 2, handle_size, handle_size),  # Right edge
            QtCore.QRect(rect.center().x() - handle_size // 2, rect.bottom() - 5 - handle_size // 2, handle_size, handle_size),  # Bottom edge
            QtCore.QRect(rect.left() + 5 - handle_size // 2, rect.center().y() - handle_size // 2, handle_size, handle_size)  # Left edge
        ]

    def _is_on_handle(self, pos):
        return self._get_handle_index(pos) is not None

    def _get_handle_index(self, pos):
        handles = self._get_handles(self.rect_roi)
        for i, handle in enumerate(handles):
            if handle.contains(pos):
                return i
        return None

    def _get_resize_direction(self, pos):
        handle_index = self._get_handle_index(pos)
        if handle_index == 0:
            return 'topleft'
        elif handle_index == 1:
            return 'topright'
        elif handle_index == 2:
            return 'bottomleft'
        elif handle_index == 3:
            return 'bottomright'
        elif handle_index == 4:
            return 'top'
        elif handle_index == 5:
            return 'right'
        elif handle_index == 6:
            return 'bottom'
        elif handle_index == 7:
            return 'left'
        return None
    
    def _resize_rect(self, pos):
        if not self.resize_direction:
            return

        if self.resize_direction == 'topleft':
            self.rect_roi.setTopLeft(pos)
        elif self.resize_direction == 'topright':
            self.rect_roi.setTopRight(pos)
        elif self.resize_direction == 'bottomleft':
            self.rect_roi.setBottomLeft(pos)
        elif self.resize_direction == 'bottomright':
            self.rect_roi.setBottomRight(pos)
        elif self.resize_direction == 'top':
            self.rect_roi.setTop(pos.y())
        elif self.resize_direction == 'right':
            self.rect_roi.setRight(pos.x())
        elif self.resize_direction == 'bottom':
            self.rect_roi.setBottom(pos.y())
        elif self.resize_direction == 'left':
            self.rect_roi.setLeft(pos.x())

        self.rect_roi = self.rect_roi.normalized()
        self.crop_rect_changed.emit(self.rect_roi.x(), self.rect_roi.y(), self.rect_roi.width(), self.rect_roi.height())


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("QMainWindow {\n"
"                background-color: rgb(255, 255, 255); /* Dark background for the main window */\n"
"            }\n"
"\n"
"            QLabel, QPushButton, QTextEdit {\n"
"                color: #ffffff; /* White text for readability */\n"
"                background-color: #333333; /* Slightly lighter dark gray for widgets */\n"
"                border: 1px solid #444444;\n"
"                padding: 5px;\n"
"                border-radius: 4px;\n"
"            }\n"
"\n"
"            QTabWidget::pane { /* The tab widget frame */\n"
"                border-top: 2px solid #333333;\n"
"            }\n"
"\n"
"            QTabBar::tab {\n"
"                background: #2b2b2b;\n"
"                color: #ccc;\n"
"                border: 2px solid #333333;\n"
"                border-bottom-color: #333333; /* same as the pane color */\n"
"                border-top-left-radius: 4px;\n"
"                border-top-right-radius: 4px;\n"
"                min-width: 8ex;\n"
"                padding: 5px;\n"
"            }\n"
"\n"
"            QTabBar::tab:selected, QTabBar::tab:hover {\n"
"                background: #3c3c3c;\n"
"                color: #ffffff;\n"
"                border-color: #0057b7; /* Blue border for selected/hover */\n"
"            }\n"
"\n"
"            QTabBar::tab:selected {\n"
"                border-color: #333333;\n"
"                border-bottom-color: #3c3c3c; /* same as pane color */\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background-color: #505050;\n"
"                border: 3px solid #0066cc;; /* Blue border for button hover */\n"
"            }\n"
"\n"
"             QMessageBox {\n"
"                    background-color: #ffffff; /* White background for the message box */\n"
"                    color: rgb(255, 255, 255); /* Black text for general content */\n"
"                }\n"
"            QMessageBox QPushButton {\n"
"                    background-color: #8c8c8c;\n"
"                    border: none;\n"
"                   }\n"
"            QMessageBox QLabel {\n"
"                    background-color: #ffffff; /* White background for the message box */\n"
"                    color: rgb(0, 0, 0); /* Explicitly setting label text color to black */\n"
"                    border: none;\n"
"                }")
        self.centralWidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1920, 1080))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("            QMainWindow {\n"
"                background-color: #333333; /* Dark background for the main window */\n"
"            }\n"
"\n"
"            QGroupBox, QPushButton, QTextEdit {\n"
"                color: black; /* White text for readability */\n"
"                background-color: #e7e7e7; /* Slightly lighter dark gray for widgets */\n"
"                border: 1px solid #444444;\n"
"                padding: 5px;\n"
"                border-radius: 4px;\n"
"            }\n"
"    \n"
"            QTabWidget::pane { /* The tab widget frame */\n"
"                border-top: 2px solid #f3f3f3;\n"
"            }\n"
"            QTabBar::tab {\n"
"                background: #f3f3f3;\n"
"                color: rgb(0, 0, 0);\n"
"                border: 1px;\n"
"                min-width: 8ex;\n"
"                padding: 5px;\n"
"            }\n"
"\n"
"            QTabBar::tab:selected, QTabBar::tab:hover {\n"
"                background: #e7e7e7;\n"
"                border-top: 3px solid #0f52ba;\n"
"            }\n"
"\n"
"\n"
"            QPushButton:hover {\n"
"                background-color: #cae1ff;\n"
"                border: 1px solid #0066cc;; /* Blue border for button hover */\n"
"            }\n"
"\n"
"QScrollBar:vertical {\n"
"                background: #2e2e2e;\n"
"                width: 14px;\n"
"                margin: 15px 3px 15px 3px;\n"
"                border: 1px solid #222222;\n"
"                border-radius: 5px;\n"
"            }\n"
"\n"
"QScrollBar::handle:vertical {\n"
"                background: #5c90d2;\n"
"                min-height: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"                background: #787878;\n"
"            }\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                background: none;\n"
"            }\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }\n"
"\n"
"             QRadioButton {\n"
"                color: #b1b1b1; /* Default text color */\n"
"                spacing: 5px; /* Spacing around text and icon */\n"
"            }\n"
"            QRadioButton::indicator {\n"
"                width: 13px;\n"
"                height: 13px;\n"
"                border-radius: 7px; /* Circular indicators */\n"
"            }\n"
"            QRadioButton::indicator:unchecked {\n"
"                background-color: #cae1ff; /* Light gray background when unchecked */\n"
"                    border: 1px solid #0066cc; /* Gray border */\n"
"            }\n"
"            QRadioButton::indicator:checked {\n"
"                background-color: #5c90d2; /* Blue background when checked */\n"
"                border: 1px solid #0066cc; /* Darker blue border */\n"
"            }\n"
"\n"
"            QRadioButton::indicator:hover {\n"
"                background-color: #5c90d2; /* Darker grey background when checked */\n"
"                border: 2px solid #0066cc; /* White border when checked */\n"
"            }\n"
"            QRadioButton::indicator:checked:hover {\n"
"                background-color: #5c90d2; /* Darker grey background when checked */\n"
"                border: 1px solid #0066cc; /* White border when checked */\n"
"            }\n"
"QMessageBox {\n"
"                    background-color: #ffffff; /* White background for the message box */\n"
"                    color: rgb(255, 255, 255); /* Black text for general content */\n"
"                }\n"
"            QMessageBox QPushButton {\n"
"                    background-color: #8c8c8c;\n"
"                    border: none;\n"
"                   }\n"
"            QMessageBox QLabel {\n"
"                    background-color: #ffffff; /* White background for the message box */\n"
"                    color: rgb(0, 0, 0); /* Explicitly setting label text color to black */\n"
"                    border: none;\n"
"                }")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Onl = QtWidgets.QWidget()
        self.tab_Onl.setObjectName("tab_Onl")
        self.label_img_out = ClickableLabel(parent=self.tab_Onl)
        self.label_img_out.setGeometry(QtCore.QRect(20, 100, 1200, 900))
        self.label_img_out.setStyleSheet("border-radius: 0px;\n"
"border: 1px solid rgb(0, 0, 0);\n"
"background-color: rgb(182, 182, 182);")
        self.label_img_out.setText("")
        self.label_img_out.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_img_out.setObjectName("label_img_out")
        self.listWidget = QtWidgets.QListWidget(parent=self.tab_Onl)
        self.listWidget.setViewMode(QtWidgets.QListWidget.ViewMode.IconMode)
        self.listWidget.setFlow(QtWidgets.QListWidget.Flow.LeftToRight)
        self.listWidget.setIconSize(QtCore.QSize(80, 80))
        self.listWidget.setSpacing(25)
        self.listWidget.setGeometry(QtCore.QRect(1250, 250, 631, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.listWidget.setStyleSheet("")
        self.listWidget.setObjectName("listWidget")
        self.label_Roi = QtWidgets.QLabel(parent=self.tab_Onl)
        self.label_Roi.setGeometry(QtCore.QRect(940, 100, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Roi.setFont(font)
        self.label_Roi.setStyleSheet("background-color: none;\n"
"border:none;\n"
"color: rgb(255, 0, 0);")
        self.label_Roi.setText("")
        self.label_Roi.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_Roi.setObjectName("label_Roi")
        self.bnDetect = QtWidgets.QPushButton(parent=self.tab_Onl)
        self.bnDetect.setEnabled(True)
        self.bnDetect.setGeometry(QtCore.QRect(1220, 900, 681, 101))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        self.bnDetect.setFont(font)
        self.bnDetect.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.bnDetect.setStyleSheet("border-radius: 0px")
        self.bnDetect.setObjectName("bnDetect")
        self.label_2 = QtWidgets.QLabel(parent=self.tab_Onl)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 1200, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 0);\n"
"border-radius: 0px;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(parent=self.tab_Onl)
        self.widget.setGeometry(QtCore.QRect(1220, 20, 681, 531))
        self.widget.setStyleSheet("\n"
"border: 1px solid rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.bnSaveRoi = QtWidgets.QPushButton(parent=self.widget)
        self.bnSaveRoi.setEnabled(True)
        self.bnSaveRoi.setGeometry(QtCore.QRect(30, 440, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.bnSaveRoi.setFont(font)
        self.bnSaveRoi.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.bnSaveRoi.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.bnSaveRoi.setStyleSheet("")
        self.bnSaveRoi.setObjectName("bnSaveRoi")
        self.bnSaveTemplate = QtWidgets.QPushButton(parent=self.widget)
        self.bnSaveTemplate.setEnabled(True)
        self.bnSaveTemplate.setGeometry(QtCore.QRect(200, 440, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.bnSaveTemplate.setFont(font)
        self.bnSaveTemplate.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.bnSaveTemplate.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.bnSaveTemplate.setStyleSheet("")
        self.bnSaveTemplate.setObjectName("bnSaveTemplate")
        self.bnLoadTemplate = QtWidgets.QPushButton(parent=self.widget)
        self.bnLoadTemplate.setEnabled(True)
        self.bnLoadTemplate.setGeometry(QtCore.QRect(370, 440, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.bnLoadTemplate.setFont(font)
        self.bnLoadTemplate.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.bnLoadTemplate.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.bnLoadTemplate.setStyleSheet("")
        self.bnLoadTemplate.setObjectName("bnLoadTemplate")
        self.bnLoadImg = QtWidgets.QPushButton(parent=self.widget)
        self.bnLoadImg.setEnabled(True)
        self.bnLoadImg.setGeometry(QtCore.QRect(540, 440, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.bnLoadImg.setFont(font)
        self.bnLoadImg.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.bnLoadImg.setStyleSheet("")
        self.bnLoadImg.setObjectName("bnLoadImg")
        self.label_temp = QtWidgets.QLabel(parent=self.widget)
        self.label_temp.setGeometry(QtCore.QRect(450, 20, 211, 201))
        self.label_temp.setStyleSheet("background-color: rgb(182, 182, 182);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.label_temp.setText("")
        self.label_temp.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_temp.setObjectName("label_temp")
        self.checkBoxTemp = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBoxTemp.setGeometry(QtCore.QRect(30, 390, 101, 31))
        self.checkBoxTemp.stateChanged.connect(self.active_draw)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxTemp.setFont(font)
        self.checkBoxTemp.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.checkBoxTemp.setAutoFillBackground(False)
        self.checkBoxTemp.setStyleSheet("border:none;")
        self.checkBoxTemp.setObjectName("checkBoxTemp")
        self.label_template_dir = QtWidgets.QLabel(parent=self.widget)
        self.label_template_dir.setGeometry(QtCore.QRect(200, 390, 461, 31))
        self.label_template_dir.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_template_dir.setText("")
        self.label_template_dir.setObjectName("label_template_dir")
        self.label_check = QtWidgets.QLabel(parent=self.widget)
        self.label_check.setGeometry(QtCore.QRect(30, 20, 401, 201))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setKerning(True)
        self.label_check.setFont(font)
        self.label_check.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"background-color: rgb(85, 170, 0);\n"
"border-radius: 0px;")
        self.label_check.setText("")
        self.label_check.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_check.setIndent(60)
        self.label_check.setObjectName("label_check")
        self.label_time = QtWidgets.QLabel(parent=self.widget)
        self.label_time.setGeometry(QtCore.QRect(30, 180, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("border: none;\n"
"background-color:none;\n"
"color: rgb(0, 0, 0);")
        self.label_time.setText("")
        self.label_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"background-color: none;\n"
"border-radius: 0px;")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.widget_3 = QtWidgets.QWidget(parent=self.tab_Onl)
        self.widget_3.setGeometry(QtCore.QRect(1220, 550, 681, 351))
        self.widget_3.setStyleSheet("\n"
"border: 1px solid rgb(0, 0, 0);")
        self.widget_3.setObjectName("widget_3")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_3)
        self.stackedWidget.setGeometry(QtCore.QRect(80, 60, 531, 281))
        self.stackedWidget.setStyleSheet("border:none;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.comboBox_oval = QtWidgets.QComboBox(parent=self.page_0)
        self.comboBox_oval.setGeometry(QtCore.QRect(340, 10, 171, 31))
        self.comboBox_oval.setStyleSheet("QComboBox {\n"
"                border: 1px solid ;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                min-width: 6em;\n"
"                background-color: none;\n"
"            }\n"
"\n"
"            QComboBox:hover {\n"
"                background-color: #cae1ff;\n"
"                border: 1px solid #0066cc; /* Blue border for button hover */\n"
"            }\n"
"\n"
"            QComboBox::drop-down {\n"
"                subcontrol-origin: padding;\n"
"                subcontrol-position: top right;\n"
"                width: 25px;\n"
"                border-left: 1px solid;\n"
"                border-top-right-radius: 3px;\n"
"                border-bottom-right-radius: 3px;\n"
"            }\n"
"\n"
"            QComboBox::down-arrow {\n"
"                image: url(D:/Pharma3/icon/icons8-arrow-down);\n"
"                width: 14px;\n"
"                height: 14px;\n"
"                margin-top: 2px;    \n"
"            }\n"
"\n"
"          ")
        self.comboBox_oval.setObjectName("comboBox_oval")
        self.comboBox_oval.addItem("")
        self.comboBox_oval.addItem("")
        self.comboBox_oval.addItem("")
        self.comboBox_oval.addItem("")
        self.comboBox_oval.addItem("")
        self.label_3 = QtWidgets.QLabel(parent=self.page_0)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);\n"
"border: none;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.widget_0 = QtWidgets.QWidget(parent=self.page_0)
        self.widget_0.setGeometry(QtCore.QRect(30, 60, 481, 201))
        self.widget_0.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(0, 0, 0)")
        self.widget_0.setObjectName("widget_0")
        self.Eccentricity_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.Eccentricity_0.setEnabled(True)
        self.Eccentricity_0.setGeometry(QtCore.QRect(390, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Eccentricity_0.setFont(font)
        self.Eccentricity_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Eccentricity_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Eccentricity_0.setObjectName("Eccentricity_0")
        self.Threshold_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.Threshold_0.setEnabled(True)
        self.Threshold_0.setGeometry(QtCore.QRect(130, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Threshold_0.setFont(font)
        self.Threshold_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Threshold_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Threshold_0.setObjectName("Threshold_0")
        self.label_17 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_17.setGeometry(QtCore.QRect(10, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_17.setObjectName("label_17")
        self.label_16 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_16.setGeometry(QtCore.QRect(10, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_16.setObjectName("label_16")
        self.Broken_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.Broken_0.setEnabled(True)
        self.Broken_0.setGeometry(QtCore.QRect(130, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Broken_0.setFont(font)
        self.Broken_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Broken_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Broken_0.setObjectName("Broken_0")
        self.label_19 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_19.setGeometry(QtCore.QRect(270, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_19.setObjectName("label_19")
        self.ROI_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.ROI_0.setEnabled(True)
        self.ROI_0.setGeometry(QtCore.QRect(130, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.ROI_0.setFont(font)
        self.ROI_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.ROI_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ROI_0.setObjectName("ROI_0")
        self.label_25 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_25.setObjectName("label_25")
        self.save0 = QtWidgets.QPushButton(parent=self.widget_0)
        self.save0.setGeometry(QtCore.QRect(400, 170, 75, 24))
        self.save0.setStyleSheet("QPushButton:hover {\n"
"                background-color: #cae1ff;\n"
"                border: 1px solid #0066cc;; /* Blue border for button hover */\n"
"            }")
        self.save0.setObjectName("save0")
        self.label_34 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_34.setGeometry(QtCore.QRect(270, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_34.setObjectName("label_34")
        self.maxBlob_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.maxBlob_0.setEnabled(True)
        self.maxBlob_0.setGeometry(QtCore.QRect(390, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.maxBlob_0.setFont(font)
        self.maxBlob_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.maxBlob_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.maxBlob_0.setObjectName("maxBlob_0")
        self.minBlob_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.minBlob_0.setEnabled(True)
        self.minBlob_0.setGeometry(QtCore.QRect(390, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.minBlob_0.setFont(font)
        self.minBlob_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.minBlob_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.minBlob_0.setObjectName("minBlob_0")
        self.label_33 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_33.setGeometry(QtCore.QRect(270, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_33.setObjectName("label_33")
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label_4 = QtWidgets.QLabel(parent=self.page_1)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);\n"
"border: none;")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.comboBox_circle = QtWidgets.QComboBox(parent=self.page_1)
        self.comboBox_circle.setGeometry(QtCore.QRect(340, 10, 171, 31))
        self.comboBox_circle.setStyleSheet("QComboBox {\n"
"                border: 1px solid ;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                min-width: 6em;\n"
"                background-color: none;\n"
"            }\n"
"\n"
"            QComboBox:hover {\n"
"                background-color: #cae1ff;\n"
"                border: 1px solid #0066cc; /* Blue border for button hover */\n"
"            }\n"
"\n"
"            QComboBox::drop-down {\n"
"                subcontrol-origin: padding;\n"
"                subcontrol-position: top right;\n"
"                width: 25px;\n"
"                border-left: 1px solid;\n"
"                border-top-right-radius: 3px;\n"
"                border-bottom-right-radius: 3px;\n"
"            }\n"
"\n"
"            QComboBox::down-arrow {\n"
"                image: url(D:/Pharma3/icon/icons8-arrow-down);\n"
"                width: 14px;\n"
"                height: 14px;\n"
"                margin-top: 2px;    \n"
"            }\n"
"\n"
"          ")
        self.comboBox_circle.setObjectName("comboBox_circle")
        self.comboBox_circle.addItem("")
        self.comboBox_circle.addItem("")
        self.comboBox_circle.addItem("")
        self.comboBox_circle.addItem("")
        self.comboBox_circle.addItem("")
        self.comboBox_circle.addItem("")
        self.widget_1 = QtWidgets.QWidget(parent=self.page_1)
        self.widget_1.setGeometry(QtCore.QRect(30, 60, 481, 201))
        self.widget_1.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(0, 0, 0)")
        self.widget_1.setObjectName("widget_1")
        self.Eccentricity_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.Eccentricity_1.setEnabled(True)
        self.Eccentricity_1.setGeometry(QtCore.QRect(130, 160, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Eccentricity_1.setFont(font)
        self.Eccentricity_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Eccentricity_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Eccentricity_1.setObjectName("Eccentricity_1")
        self.Threshold_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.Threshold_1.setEnabled(True)
        self.Threshold_1.setGeometry(QtCore.QRect(130, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Threshold_1.setFont(font)
        self.Threshold_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Threshold_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Threshold_1.setObjectName("Threshold_1")
        self.label_18 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_18.setGeometry(QtCore.QRect(10, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_20.setGeometry(QtCore.QRect(270, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_20.setObjectName("label_20")
        self.Broken_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.Broken_1.setEnabled(True)
        self.Broken_1.setGeometry(QtCore.QRect(390, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Broken_1.setFont(font)
        self.Broken_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Broken_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Broken_1.setObjectName("Broken_1")
        self.label_21 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_21.setGeometry(QtCore.QRect(10, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_21.setObjectName("label_21")
        self.save1 = QtWidgets.QPushButton(parent=self.widget_1)
        self.save1.setGeometry(QtCore.QRect(400, 170, 75, 24))
        self.save1.setObjectName("save1")
        self.min_area_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.min_area_1.setEnabled(True)
        self.min_area_1.setGeometry(QtCore.QRect(130, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.min_area_1.setFont(font)
        self.min_area_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.min_area_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.min_area_1.setObjectName("min_area_1")
        self.label_27 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_27.setGeometry(QtCore.QRect(10, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_27.setObjectName("label_27")
        self.label_30 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_30.setGeometry(QtCore.QRect(10, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_30.setObjectName("label_30")
        self.ROI_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.ROI_1.setEnabled(True)
        self.ROI_1.setGeometry(QtCore.QRect(130, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.ROI_1.setFont(font)
        self.ROI_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.ROI_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ROI_1.setObjectName("ROI_1")
        self.label_31 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_31.setGeometry(QtCore.QRect(270, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_31.setObjectName("label_31")
        self.maxBlob_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.maxBlob_1.setEnabled(True)
        self.maxBlob_1.setGeometry(QtCore.QRect(390, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.maxBlob_1.setFont(font)
        self.maxBlob_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.maxBlob_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.maxBlob_1.setObjectName("maxBlob_1")
        self.label_32 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_32.setGeometry(QtCore.QRect(270, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_32.setObjectName("label_32")
        self.minBlob_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.minBlob_1.setEnabled(True)
        self.minBlob_1.setGeometry(QtCore.QRect(390, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.minBlob_1.setFont(font)
        self.minBlob_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.minBlob_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.minBlob_1.setObjectName("minBlob_1")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_5 = QtWidgets.QLabel(parent=self.page_2)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);\n"
"border: none;")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.comboBox_capsule = QtWidgets.QComboBox(parent=self.page_2)
        self.comboBox_capsule.setGeometry(QtCore.QRect(340, 10, 171, 31))
        self.comboBox_capsule.setStyleSheet("QComboBox {\n"
"                border: 1px solid ;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                min-width: 6em;\n"
"                background-color: none;\n"
"            }\n"
"\n"
"            QComboBox:hover {\n"
"                background-color: #cae1ff;\n"
"                border: 1px solid #0066cc; /* Blue border for button hover */\n"
"            }\n"
"\n"
"            QComboBox::drop-down {\n"
"                subcontrol-origin: padding;\n"
"                subcontrol-position: top right;\n"
"                width: 25px;\n"
"                border-left: 1px solid;\n"
"                border-top-right-radius: 3px;\n"
"                border-bottom-right-radius: 3px;\n"
"            }\n"
"\n"
"            QComboBox::down-arrow {\n"
"                image: url(D:/Pharma3/icon/icons8-arrow-down);\n"
"                width: 14px;\n"
"                height: 14px;\n"
"                margin-top: 2px;    \n"
"            }\n"
"\n"
"          ")
        self.comboBox_capsule.setObjectName("comboBox_capsule")
        self.comboBox_capsule.addItem("")
        self.comboBox_capsule.addItem("")
        self.comboBox_capsule.addItem("")
        self.comboBox_capsule.addItem("")
        self.widget_2 = QtWidgets.QWidget(parent=self.page_2)
        self.widget_2.setGeometry(QtCore.QRect(30, 60, 481, 201))
        self.widget_2.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(0, 0, 0)")
        self.widget_2.setObjectName("widget_2")
        self.value = QtWidgets.QLineEdit(parent=self.widget_2)
        self.value.setEnabled(True)
        self.value.setGeometry(QtCore.QRect(390, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.value.setFont(font)
        self.value.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.value.setObjectName("value")
        self.Threshold_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.Threshold_2.setEnabled(True)
        self.Threshold_2.setGeometry(QtCore.QRect(130, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Threshold_2.setFont(font)
        self.Threshold_2.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Threshold_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Threshold_2.setObjectName("Threshold_2")
        self.label_22 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_22.setGeometry(QtCore.QRect(10, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_23.setGeometry(QtCore.QRect(270, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_24.setGeometry(QtCore.QRect(270, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_24.setObjectName("label_24")
        self.ROI_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.ROI_2.setEnabled(True)
        self.ROI_2.setGeometry(QtCore.QRect(130, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.ROI_2.setFont(font)
        self.ROI_2.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.ROI_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ROI_2.setObjectName("ROI_2")
        self.label_26 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_26.setObjectName("label_26")
        self.save2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.save2.setGeometry(QtCore.QRect(400, 170, 75, 24))
        self.save2.setObjectName("save2")
        self.label_28 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_28.setGeometry(QtCore.QRect(10, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_28.setObjectName("label_28")
        self.min_area_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.min_area_2.setEnabled(True)
        self.min_area_2.setGeometry(QtCore.QRect(130, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.min_area_2.setFont(font)
        self.min_area_2.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.min_area_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.min_area_2.setObjectName("min_area_2")
        self.label_29 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_29.setGeometry(QtCore.QRect(270, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_29.setObjectName("label_29")
        self.max_area_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.max_area_2.setEnabled(True)
        self.max_area_2.setGeometry(QtCore.QRect(390, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.max_area_2.setFont(font)
        self.max_area_2.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.max_area_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.max_area_2.setObjectName("max_area_2")
        self.hue = QtWidgets.QLineEdit(parent=self.widget_2)
        self.hue.setEnabled(True)
        self.hue.setGeometry(QtCore.QRect(390, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.hue.setFont(font)
        self.hue.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.hue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hue.setObjectName("hue")
        self.stackedWidget.addWidget(self.page_2)
        self.comboBox_type = QtWidgets.QComboBox(parent=self.widget_3)
        self.comboBox_type.setGeometry(QtCore.QRect(30, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_type.setFont(font)
        self.comboBox_type.setStyleSheet("QComboBox {\n"
"                border: 1px solid ;\n"
"                border-radius: 5px;\n"
"                padding: 5px;\n"
"                min-width: 6em;\n"
"                background-color: none;\n"
"            }\n"
"\n"
"            QComboBox:hover {\n"
"                background-color: #cae1ff;\n"
"                border: 1px solid #0066cc; /* Blue border for button hover */\n"
"            }\n"
"\n"
"            QComboBox::drop-down {\n"
"                subcontrol-origin: padding;\n"
"                subcontrol-position: top right;\n"
"                width: 25px;\n"
"                border-left: 1px solid;\n"
"                border-top-right-radius: 3px;\n"
"                border-bottom-right-radius: 3px;\n"
"            }\n"
"\n"
"            QComboBox::down-arrow {\n"
"                image: url(D:/Pharma3/icon/icons8-arrow-down);\n"
"                width: 14px;\n"
"                height: 14px;\n"
"                margin-top: 2px;    \n"
"            }\n"
"\n"
"          ")
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.label_logo = QtWidgets.QLabel(parent=self.tab_Onl)
        self.label_logo.setGeometry(QtCore.QRect(1140, 20, 81, 81))
        self.label_logo.setStyleSheet("background-color: none;\n"
"border:none")
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.widget_3.raise_()
        self.widget.raise_()
        self.label_2.raise_()
        self.label_img_out.raise_()
        self.listWidget.raise_()
        self.label_Roi.raise_()
        self.bnDetect.raise_()
        self.label_logo.raise_()
        self.tabWidget.addTab(self.tab_Onl, "")
        self.tab_Off = QtWidgets.QWidget()
        self.tab_Off.setObjectName("tab_Off")
        self.groupInit = QtWidgets.QGroupBox(parent=self.tab_Off)
        self.groupInit.setGeometry(QtCore.QRect(730, 330, 590, 260))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        self.groupInit.setFont(font)
        self.groupInit.setStyleSheet("")
        self.groupInit.setTitle("")
        self.groupInit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupInit.setObjectName("groupInit")
        self.bnEnum = QtWidgets.QPushButton(parent=self.groupInit)
        self.bnEnum.setGeometry(QtCore.QRect(90, 180, 181, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.bnEnum.setFont(font)
        self.bnEnum.setObjectName("bnEnum")
        self.bnOpen = QtWidgets.QPushButton(parent=self.groupInit)
        self.bnOpen.setGeometry(QtCore.QRect(320, 180, 181, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.bnOpen.setFont(font)
        self.bnOpen.setObjectName("bnOpen")
        self.ComboDevices = QtWidgets.QComboBox(parent=self.groupInit)
        self.ComboDevices.setGeometry(QtCore.QRect(40, 90, 521, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.ComboDevices.setFont(font)
        self.ComboDevices.setStyleSheet("color: rgb(0, 0, 0);")
        self.ComboDevices.setObjectName("ComboDevices")
        self.label = QtWidgets.QLabel(parent=self.groupInit)
        self.label.setGeometry(QtCore.QRect(200, 10, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);\n"
"border: none;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab_Off, "")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bnDetect.setText(_translate("MainWindow", "DETECT"))
        self.label_2.setText(_translate("MainWindow", "VISION SYSTEM"))
        self.bnSaveRoi.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bnSaveRoi.setText(_translate("MainWindow", "Save\n"
"ROI"))
        self.bnSaveTemplate.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bnSaveTemplate.setText(_translate("MainWindow", "Save\n"
"Template"))
        self.bnLoadTemplate.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bnLoadTemplate.setText(_translate("MainWindow", "Load\n"
"Template"))
        self.bnLoadImg.setText(_translate("MainWindow", "Load\n"
"Image"))
        self.checkBoxTemp.setText(_translate("MainWindow", "     DRAW"))
        self.label_6.setText(_translate("MainWindow", "RESULT"))
        self.comboBox_oval.setItemText(0, _translate("MainWindow", "Matching Template"))
        self.comboBox_oval.setItemText(1, _translate("MainWindow", "Check Crack"))
        self.comboBox_oval.setItemText(2, _translate("MainWindow", "Check Blob"))
        self.comboBox_oval.setItemText(3, _translate("MainWindow", "Check Oval"))
        self.comboBox_oval.setItemText(4, _translate("MainWindow", "Final"))
        self.label_3.setText(_translate("MainWindow", "Configuration Oval"))
        self.Eccentricity_0.setText(_translate("MainWindow", "0.3939"))
        self.Threshold_0.setText(_translate("MainWindow", "0.91"))
        self.label_17.setText(_translate("MainWindow", "Threshold:"))
        self.label_16.setText(_translate("MainWindow", "Broken:"))
        self.Broken_0.setText(_translate("MainWindow", "7"))
        self.label_19.setText(_translate("MainWindow", "Eccentricity:"))
        self.ROI_0.setText(_translate("MainWindow", "1"))
        self.label_25.setText(_translate("MainWindow", "ROI:"))
        self.save0.setText(_translate("MainWindow", "Save"))
        self.label_34.setText(_translate("MainWindow", "MinBlobArea:"))
        self.maxBlob_0.setText(_translate("MainWindow", "2000"))
        self.minBlob_0.setText(_translate("MainWindow", "10"))
        self.label_33.setText(_translate("MainWindow", "MaxBlobArea:"))
        self.label_4.setText(_translate("MainWindow", "Configuration Circle"))
        self.comboBox_circle.setItemText(0, _translate("MainWindow", "Matching Template"))
        self.comboBox_circle.setItemText(1, _translate("MainWindow", "Check Area"))
        self.comboBox_circle.setItemText(2, _translate("MainWindow", "Check Circularity"))
        self.comboBox_circle.setItemText(3, _translate("MainWindow", "Check Blob"))
        self.comboBox_circle.setItemText(4, _translate("MainWindow", "Check Cracks"))
        self.comboBox_circle.setItemText(5, _translate("MainWindow", "Final"))
        self.Eccentricity_1.setText(_translate("MainWindow", "0.87"))
        self.Threshold_1.setText(_translate("MainWindow", "0.9"))
        self.label_18.setText(_translate("MainWindow", "Threshold:"))
        self.label_20.setText(_translate("MainWindow", "Cracks:"))
        self.Broken_1.setText(_translate("MainWindow", "7"))
        self.label_21.setText(_translate("MainWindow", "Eccentricity:"))
        self.save1.setText(_translate("MainWindow", "Save"))
        self.min_area_1.setText(_translate("MainWindow", "5000"))
        self.label_27.setText(_translate("MainWindow", "Min Area:"))
        self.label_30.setText(_translate("MainWindow", "ROI:"))
        self.ROI_1.setText(_translate("MainWindow", "1"))
        self.label_31.setText(_translate("MainWindow", "MaxBlobArea:"))
        self.maxBlob_1.setText(_translate("MainWindow", "3000"))
        self.label_32.setText(_translate("MainWindow", "MinBlobArea:"))
        self.minBlob_1.setText(_translate("MainWindow", "20"))
        self.label_5.setText(_translate("MainWindow", "Configuration Capsule"))
        self.comboBox_capsule.setItemText(0, _translate("MainWindow", "Matching Template"))
        self.comboBox_capsule.setItemText(1, _translate("MainWindow", "Count Pixel"))
        self.comboBox_capsule.setItemText(2, _translate("MainWindow", "Check Area"))
        self.comboBox_capsule.setItemText(3, _translate("MainWindow", "Final"))
        self.value.setText(_translate("MainWindow", "20"))
        self.Threshold_2.setText(_translate("MainWindow", "0.85"))
        self.label_22.setText(_translate("MainWindow", "Threshold:"))
        self.label_23.setText(_translate("MainWindow", "Hue:"))
        self.label_24.setText(_translate("MainWindow", "Value:"))
        self.ROI_2.setText(_translate("MainWindow", "1"))
        self.label_26.setText(_translate("MainWindow", "ROI:"))
        self.save2.setText(_translate("MainWindow", "Save"))
        self.label_28.setText(_translate("MainWindow", "Min area:"))
        self.min_area_2.setText(_translate("MainWindow", "1000"))
        self.label_29.setText(_translate("MainWindow", "Max area:"))
        self.max_area_2.setText(_translate("MainWindow", "3000"))
        self.hue.setText(_translate("MainWindow", "20"))
        self.comboBox_type.setItemText(0, _translate("MainWindow", "Oval Tablet"))
        self.comboBox_type.setItemText(1, _translate("MainWindow", "Circle Tablet"))
        self.comboBox_type.setItemText(2, _translate("MainWindow", "Capsule"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Onl), _translate("MainWindow", "Process Image"))
        self.bnEnum.setText(_translate("MainWindow", "Search Device"))
        self.bnOpen.setText(_translate("MainWindow", "Open Device"))
        self.label.setText(_translate("MainWindow", "Initialization"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Off), _translate("MainWindow", "Connect Camera"))

    def active_draw(self):
        if self.checkBoxTemp.isChecked() and not self.label_img_out.pixmap().isNull():
            self.label_img_out.active_draw_rect = True
        else:
            self.label_img_out.rect_roi = None  # Reset the rectangle
            self.label_img_out.update()
            self.label_img_out.active_draw_rect = False
            self.label_temp.setPixmap(QtGui.QPixmap())