# Form implementation generated from reading ui file 'Settings_Cam.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(618, 526)
        Dialog.setStyleSheet("            QMainWindow {\n"
"                background-color: #333333; /* Dark background for the main window */\n"
"            }\n"
"\n"
"            QGroupBox, QPushButton, QTextEdit {\n"
"                color: black; /* White text for readability */\n"
"                background-color: #e7e7e7; /* Slightly lighter dark gray for widgets */\n"
"                border: 1px solid #444444;\n"
"                padding: 5px;\n"
"                border-radius: 4px;\n"
"            }\n"
"    \n"
"            QTabWidget::pane { /* The tab widget frame */\n"
"                border-top: 2px solid #f3f3f3;\n"
"            }\n"
"            QTabBar::tab {\n"
"                background: #f3f3f3;\n"
"                color: rgb(0, 0, 0);\n"
"                border: 1px;\n"
"                min-width: 8ex;\n"
"                padding: 5px;\n"
"            }\n"
"\n"
"            QTabBar::tab:selected, QTabBar::tab:hover {\n"
"                background: #e7e7e7;\n"
"                border-top: 3px solid #0f52ba;\n"
"            }\n"
"\n"
"\n"
"            QPushButton:hover {\n"
"                background-color: #cae1ff;\n"
"                border: 1px solid #0066cc;; /* Blue border for button hover */\n"
"            }\n"
"\n"
"QScrollBar:vertical {\n"
"                background: #2e2e2e;\n"
"                width: 14px;\n"
"                margin: 15px 3px 15px 3px;\n"
"                border: 1px solid #222222;\n"
"                border-radius: 5px;\n"
"            }\n"
"\n"
"QScrollBar::handle:vertical {\n"
"                background: #5c90d2;\n"
"                min-height: 20px;\n"
"                border-radius: 5px;\n"
"            }\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"                background: #787878;\n"
"            }\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                background: none;\n"
"            }\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }\n"
"\n"
"             QRadioButton {\n"
"                color: #b1b1b1; /* Default text color */\n"
"                spacing: 5px; /* Spacing around text and icon */\n"
"            }\n"
"            QRadioButton::indicator {\n"
"                width: 13px;\n"
"                height: 13px;\n"
"                border-radius: 7px; /* Circular indicators */\n"
"            }\n"
"            QRadioButton::indicator:unchecked {\n"
"                background-color: #cae1ff; /* Light gray background when unchecked */\n"
"                    border: 1px solid #0066cc; /* Gray border */\n"
"            }\n"
"            QRadioButton::indicator:checked {\n"
"                background-color: #5c90d2; /* Blue background when checked */\n"
"                border: 1px solid #0066cc; /* Darker blue border */\n"
"            }\n"
"\n"
"            QRadioButton::indicator:hover {\n"
"                background-color: #5c90d2; /* Darker grey background when checked */\n"
"                border: 2px solid #0066cc; /* White border when checked */\n"
"            }\n"
"            QRadioButton::indicator:checked:hover {\n"
"                background-color: #5c90d2; /* Darker grey background when checked */\n"
"                border: 1px solid #0066cc; /* White border when checked */\n"
"            }\n"
"QMessageBox {\n"
"                    background-color: #ffffff; /* White background for the message box */\n"
"                    color: rgb(255, 255, 255); /* Black text for general content */\n"
"                }\n"
"            QMessageBox QPushButton {\n"
"                    background-color: #8c8c8c;\n"
"                    border: none;\n"
"                   }\n"
"            QMessageBox QLabel {\n"
"                    background-color: #ffffff; /* White background for the message box */\n"
"                    color: rgb(0, 0, 0); /* Explicitly setting label text color to black */\n"
"                    border: none;\n"
"                }")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 20, 571, 281))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.label_8 = QtWidgets.QLabel(parent=self.page_0)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);\n"
"border: none;")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.widget_0 = QtWidgets.QWidget(parent=self.page_0)
        self.widget_0.setGeometry(QtCore.QRect(30, 60, 521, 211))
        self.widget_0.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(0, 0, 0)")
        self.widget_0.setObjectName("widget_0")
        self.Eccentricity_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.Eccentricity_0.setEnabled(True)
        self.Eccentricity_0.setGeometry(QtCore.QRect(400, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Eccentricity_0.setFont(font)
        self.Eccentricity_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Eccentricity_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Eccentricity_0.setObjectName("Eccentricity_0")
        self.Threshold_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.Threshold_0.setEnabled(True)
        self.Threshold_0.setGeometry(QtCore.QRect(160, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Threshold_0.setFont(font)
        self.Threshold_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Threshold_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Threshold_0.setObjectName("Threshold_0")
        self.label_17 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_17.setGeometry(QtCore.QRect(40, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_17.setObjectName("label_17")
        self.label_16 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_16.setGeometry(QtCore.QRect(40, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_16.setObjectName("label_16")
        self.Broken_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.Broken_0.setEnabled(True)
        self.Broken_0.setGeometry(QtCore.QRect(160, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Broken_0.setFont(font)
        self.Broken_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Broken_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Broken_0.setObjectName("Broken_0")
        self.label_19 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_19.setGeometry(QtCore.QRect(280, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_19.setObjectName("label_19")
        self.ROI_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.ROI_0.setEnabled(True)
        self.ROI_0.setGeometry(QtCore.QRect(160, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.ROI_0.setFont(font)
        self.ROI_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.ROI_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ROI_0.setObjectName("ROI_0")
        self.label_25 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_25.setGeometry(QtCore.QRect(40, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_25.setObjectName("label_25")
        self.save0 = QtWidgets.QPushButton(parent=self.widget_0)
        self.save0.setGeometry(QtCore.QRect(400, 170, 81, 31))
        self.save0.setStyleSheet("QPushButton:hover {\n"
"                background-color: #cae1ff;\n"
"                border: 1px solid #0066cc;; /* Blue border for button hover */\n"
"            }")
        self.save0.setObjectName("save0")
        self.label_34 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_34.setGeometry(QtCore.QRect(280, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_34.setObjectName("label_34")
        self.maxBlob_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.maxBlob_0.setEnabled(True)
        self.maxBlob_0.setGeometry(QtCore.QRect(400, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.maxBlob_0.setFont(font)
        self.maxBlob_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.maxBlob_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.maxBlob_0.setObjectName("maxBlob_0")
        self.minBlob_0 = QtWidgets.QLineEdit(parent=self.widget_0)
        self.minBlob_0.setEnabled(True)
        self.minBlob_0.setGeometry(QtCore.QRect(400, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.minBlob_0.setFont(font)
        self.minBlob_0.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.minBlob_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.minBlob_0.setObjectName("minBlob_0")
        self.label_33 = QtWidgets.QLabel(parent=self.widget_0)
        self.label_33.setGeometry(QtCore.QRect(280, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_33.setObjectName("label_33")
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label_9 = QtWidgets.QLabel(parent=self.page_1)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);\n"
"border: none;")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.comboBox_circle = QtWidgets.QComboBox(parent=self.page_1)
        self.comboBox_circle.setGeometry(QtCore.QRect(340, 10, 171, 31))
        self.comboBox_circle.setObjectName("comboBox_circle")
        self.comboBox_circle.addItem("")
        self.comboBox_circle.addItem("")
        self.comboBox_circle.addItem("")
        self.comboBox_circle.addItem("")
        self.comboBox_circle.addItem("")
        self.comboBox_circle.addItem("")
        self.widget_1 = QtWidgets.QWidget(parent=self.page_1)
        self.widget_1.setGeometry(QtCore.QRect(30, 60, 481, 201))
        self.widget_1.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(0, 0, 0)")
        self.widget_1.setObjectName("widget_1")
        self.Eccentricity_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.Eccentricity_1.setEnabled(True)
        self.Eccentricity_1.setGeometry(QtCore.QRect(130, 160, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Eccentricity_1.setFont(font)
        self.Eccentricity_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Eccentricity_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Eccentricity_1.setObjectName("Eccentricity_1")
        self.Threshold_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.Threshold_1.setEnabled(True)
        self.Threshold_1.setGeometry(QtCore.QRect(130, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Threshold_1.setFont(font)
        self.Threshold_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Threshold_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Threshold_1.setObjectName("Threshold_1")
        self.label_18 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_18.setGeometry(QtCore.QRect(10, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_20.setGeometry(QtCore.QRect(270, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_20.setObjectName("label_20")
        self.Broken_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.Broken_1.setEnabled(True)
        self.Broken_1.setGeometry(QtCore.QRect(390, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Broken_1.setFont(font)
        self.Broken_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Broken_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Broken_1.setObjectName("Broken_1")
        self.label_21 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_21.setGeometry(QtCore.QRect(10, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_21.setObjectName("label_21")
        self.save1 = QtWidgets.QPushButton(parent=self.widget_1)
        self.save1.setGeometry(QtCore.QRect(400, 170, 75, 24))
        self.save1.setObjectName("save1")
        self.min_area_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.min_area_1.setEnabled(True)
        self.min_area_1.setGeometry(QtCore.QRect(130, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.min_area_1.setFont(font)
        self.min_area_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.min_area_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.min_area_1.setObjectName("min_area_1")
        self.label_27 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_27.setGeometry(QtCore.QRect(10, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_27.setObjectName("label_27")
        self.label_30 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_30.setGeometry(QtCore.QRect(10, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_30.setObjectName("label_30")
        self.ROI_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.ROI_1.setEnabled(True)
        self.ROI_1.setGeometry(QtCore.QRect(130, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.ROI_1.setFont(font)
        self.ROI_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.ROI_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ROI_1.setObjectName("ROI_1")
        self.label_31 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_31.setGeometry(QtCore.QRect(270, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_31.setObjectName("label_31")
        self.maxBlob_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.maxBlob_1.setEnabled(True)
        self.maxBlob_1.setGeometry(QtCore.QRect(390, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.maxBlob_1.setFont(font)
        self.maxBlob_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.maxBlob_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.maxBlob_1.setObjectName("maxBlob_1")
        self.label_32 = QtWidgets.QLabel(parent=self.widget_1)
        self.label_32.setGeometry(QtCore.QRect(270, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_32.setObjectName("label_32")
        self.minBlob_1 = QtWidgets.QLineEdit(parent=self.widget_1)
        self.minBlob_1.setEnabled(True)
        self.minBlob_1.setGeometry(QtCore.QRect(390, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.minBlob_1.setFont(font)
        self.minBlob_1.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.minBlob_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.minBlob_1.setObjectName("minBlob_1")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_10 = QtWidgets.QLabel(parent=self.page_2)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);\n"
"border: none;")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.comboBox_capsule = QtWidgets.QComboBox(parent=self.page_2)
        self.comboBox_capsule.setGeometry(QtCore.QRect(340, 10, 171, 31))
        self.comboBox_capsule.setObjectName("comboBox_capsule")
        self.comboBox_capsule.addItem("")
        self.comboBox_capsule.addItem("")
        self.comboBox_capsule.addItem("")
        self.comboBox_capsule.addItem("")
        self.widget_2 = QtWidgets.QWidget(parent=self.page_2)
        self.widget_2.setGeometry(QtCore.QRect(30, 60, 481, 201))
        self.widget_2.setStyleSheet("border-radius: 5px;\n"
"border: 0.5px solid rgb(0, 0, 0)")
        self.widget_2.setObjectName("widget_2")
        self.Threshold_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.Threshold_2.setEnabled(True)
        self.Threshold_2.setGeometry(QtCore.QRect(130, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.Threshold_2.setFont(font)
        self.Threshold_2.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.Threshold_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Threshold_2.setObjectName("Threshold_2")
        self.label_22 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_22.setGeometry(QtCore.QRect(10, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_22.setObjectName("label_22")
        self.ROI_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.ROI_2.setEnabled(True)
        self.ROI_2.setGeometry(QtCore.QRect(130, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.ROI_2.setFont(font)
        self.ROI_2.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.ROI_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ROI_2.setObjectName("ROI_2")
        self.label_26 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_26.setObjectName("label_26")
        self.save2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.save2.setGeometry(QtCore.QRect(400, 170, 75, 24))
        self.save2.setObjectName("save2")
        self.label_28 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_28.setGeometry(QtCore.QRect(10, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_28.setObjectName("label_28")
        self.min_area_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.min_area_2.setEnabled(True)
        self.min_area_2.setGeometry(QtCore.QRect(130, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.min_area_2.setFont(font)
        self.min_area_2.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.min_area_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.min_area_2.setObjectName("min_area_2")
        self.label_29 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_29.setGeometry(QtCore.QRect(270, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_29.setObjectName("label_29")
        self.max_area_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.max_area_2.setEnabled(True)
        self.max_area_2.setGeometry(QtCore.QRect(390, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.max_area_2.setFont(font)
        self.max_area_2.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.max_area_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.max_area_2.setObjectName("max_area_2")
        self.hue = QtWidgets.QLineEdit(parent=self.widget_2)
        self.hue.setEnabled(True)
        self.hue.setGeometry(QtCore.QRect(390, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.hue.setFont(font)
        self.hue.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.hue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hue.setObjectName("hue")
        self.label_35 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_35.setGeometry(QtCore.QRect(270, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_35.setObjectName("label_35")
        self.value = QtWidgets.QLineEdit(parent=self.widget_2)
        self.value.setEnabled(True)
        self.value.setGeometry(QtCore.QRect(390, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.value.setFont(font)
        self.value.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.value.setObjectName("value")
        self.label_36 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_36.setGeometry(QtCore.QRect(270, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("border: none;\n"
"background-color: #e7e7e7;\n"
"color: rgb(0, 0, 0);")
        self.label_36.setObjectName("label_36")
        self.stackedWidget.addWidget(self.page_2)
        self.groupParam = QtWidgets.QGroupBox(parent=Dialog)
        self.groupParam.setEnabled(True)
        self.groupParam.setGeometry(QtCore.QRect(50, 370, 521, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupParam.sizePolicy().hasHeightForWidth())
        self.groupParam.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.groupParam.setFont(font)
        self.groupParam.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.groupParam.setAutoFillBackground(False)
        self.groupParam.setStyleSheet("background-color: none;\n"
"border-radius: 5px;\n"
"border: 0.5px solid rgb(0, 0, 0)")
        self.groupParam.setTitle("")
        self.groupParam.setObjectName("groupParam")
        self.edtExposureTime = QtWidgets.QLineEdit(parent=self.groupParam)
        self.edtExposureTime.setGeometry(QtCore.QRect(90, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.edtExposureTime.setFont(font)
        self.edtExposureTime.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.edtExposureTime.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.edtExposureTime.setObjectName("edtExposureTime")
        self.label_6 = QtWidgets.QLabel(parent=self.groupParam)
        self.label_6.setGeometry(QtCore.QRect(360, 10, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_6.setStyleSheet("border: none;\n"
"background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_6.setIndent(5)
        self.label_6.setObjectName("label_6")
        self.edtGain = QtWidgets.QLineEdit(parent=self.groupParam)
        self.edtGain.setGeometry(QtCore.QRect(250, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.edtGain.setFont(font)
        self.edtGain.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.edtGain.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.edtGain.setObjectName("edtGain")
        self.label_5 = QtWidgets.QLabel(parent=self.groupParam)
        self.label_5.setGeometry(QtCore.QRect(200, 10, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_5.setStyleSheet("border: none;\n"
"background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_5.setIndent(4)
        self.label_5.setObjectName("label_5")
        self.edtFrameRate = QtWidgets.QLineEdit(parent=self.groupParam)
        self.edtFrameRate.setGeometry(QtCore.QRect(420, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.edtFrameRate.setFont(font)
        self.edtFrameRate.setStyleSheet("border: 1px solid rgb(0, 0, 0);")
        self.edtFrameRate.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.edtFrameRate.setObjectName("edtFrameRate")
        self.label_4 = QtWidgets.QLabel(parent=self.groupParam)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_4.setStyleSheet("border: none;\n"
"background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_4.setIndent(5)
        self.label_4.setObjectName("label_4")
        self.bnSetParam = QtWidgets.QPushButton(parent=self.groupParam)
        self.bnSetParam.setEnabled(True)
        self.bnSetParam.setGeometry(QtCore.QRect(420, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.bnSetParam.setFont(font)
        self.bnSetParam.setToolTip("")
        self.bnSetParam.setStyleSheet("QPushButton:hover {\n"
"                background-color: #cae1ff;\n"
"                border: 1px solid #0066cc;; /* Blue border for button hover */\n"
"            }\n"
"QPushButton {\n"
"                color: black; /* White text for readability */\n"
"                background-color: #e7e7e7; /* Slightly lighter dark gray for widgets */\n"
"                border: 1px solid #444444;\n"
"                padding: 5px;\n"
"                border-radius: 4px;\n"
"            }")
        self.bnSetParam.setObjectName("bnSetParam")
        self.label_11 = QtWidgets.QLabel(parent=Dialog)
        self.label_11.setGeometry(QtCore.QRect(30, 310, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);\n"
"border: none;")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_11.setObjectName("label_11")

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_8.setText(_translate("Dialog", "Configuration Oval"))
        self.Eccentricity_0.setText(_translate("Dialog", "0.3939"))
        self.Threshold_0.setText(_translate("Dialog", "0.91"))
        self.label_17.setText(_translate("Dialog", "Threshold:"))
        self.label_16.setText(_translate("Dialog", "Broken:"))
        self.Broken_0.setText(_translate("Dialog", "7"))
        self.label_19.setText(_translate("Dialog", "Eccentricity:"))
        self.ROI_0.setText(_translate("Dialog", "1"))
        self.label_25.setText(_translate("Dialog", "ROI:"))
        self.save0.setText(_translate("Dialog", "Save"))
        self.label_34.setText(_translate("Dialog", "MinBlobArea:"))
        self.maxBlob_0.setText(_translate("Dialog", "2000"))
        self.minBlob_0.setText(_translate("Dialog", "10"))
        self.label_33.setText(_translate("Dialog", "MaxBlobArea:"))
        self.label_9.setText(_translate("Dialog", "Configuration Circle"))
        self.comboBox_circle.setItemText(0, _translate("Dialog", "Matching Template"))
        self.comboBox_circle.setItemText(1, _translate("Dialog", "Check Area"))
        self.comboBox_circle.setItemText(2, _translate("Dialog", "Check Circularity"))
        self.comboBox_circle.setItemText(3, _translate("Dialog", "Check Blob"))
        self.comboBox_circle.setItemText(4, _translate("Dialog", "Check Cracks"))
        self.comboBox_circle.setItemText(5, _translate("Dialog", "Final"))
        self.Eccentricity_1.setText(_translate("Dialog", "0.87"))
        self.Threshold_1.setText(_translate("Dialog", "0.9"))
        self.label_18.setText(_translate("Dialog", "Threshold:"))
        self.label_20.setText(_translate("Dialog", "Cracks:"))
        self.Broken_1.setText(_translate("Dialog", "7"))
        self.label_21.setText(_translate("Dialog", "Eccentricity:"))
        self.save1.setText(_translate("Dialog", "Save"))
        self.min_area_1.setText(_translate("Dialog", "5000"))
        self.label_27.setText(_translate("Dialog", "Min Area:"))
        self.label_30.setText(_translate("Dialog", "ROI:"))
        self.ROI_1.setText(_translate("Dialog", "1"))
        self.label_31.setText(_translate("Dialog", "MaxBlobArea:"))
        self.maxBlob_1.setText(_translate("Dialog", "3000"))
        self.label_32.setText(_translate("Dialog", "MinBlobArea:"))
        self.minBlob_1.setText(_translate("Dialog", "20"))
        self.label_10.setText(_translate("Dialog", "Configuration Capsule"))
        self.comboBox_capsule.setItemText(0, _translate("Dialog", "Matching Template"))
        self.comboBox_capsule.setItemText(1, _translate("Dialog", "Count Pixel"))
        self.comboBox_capsule.setItemText(2, _translate("Dialog", "Check Area"))
        self.comboBox_capsule.setItemText(3, _translate("Dialog", "Final"))
        self.Threshold_2.setText(_translate("Dialog", "0.85"))
        self.label_22.setText(_translate("Dialog", "Threshold:"))
        self.ROI_2.setText(_translate("Dialog", "1"))
        self.label_26.setText(_translate("Dialog", "ROI:"))
        self.save2.setText(_translate("Dialog", "Save"))
        self.label_28.setText(_translate("Dialog", "Min area:"))
        self.min_area_2.setText(_translate("Dialog", "1000"))
        self.label_29.setText(_translate("Dialog", "Max area:"))
        self.max_area_2.setText(_translate("Dialog", "3000"))
        self.hue.setText(_translate("Dialog", "20"))
        self.label_35.setText(_translate("Dialog", "Value:"))
        self.value.setText(_translate("Dialog", "20"))
        self.label_36.setText(_translate("Dialog", "Hue:"))
        self.edtExposureTime.setText(_translate("Dialog", "0"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p>Frame<br/>rate:</p></body></html>"))
        self.edtGain.setText(_translate("Dialog", "0"))
        self.label_5.setText(_translate("Dialog", "Gain:"))
        self.edtFrameRate.setText(_translate("Dialog", "0"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p>Exposure<br/>time:</p></body></html>"))
        self.bnSetParam.setText(_translate("Dialog", "Save"))
        self.label_11.setText(_translate("Dialog", "Camera Parameters"))
